name: CI
on: [push, pull_request]

env:
    name: SilentPatchYK2

jobs:
    build:
        name: Build
        runs-on: windows-2022
        strategy:
            matrix:
                configuration: [Release, Shipping]

        steps:
            - name: Checkout the repository
              uses: actions/checkout@v4
              with:
                submodules: recursive
            # - name: Cache vcpkg
            #   uses: actions/cache@v4
            #   with:
            #     path: vcpkg_installed
            #     key: ${{ runner.os }}-${{ hashFiles('**/vcpkg.json') }}
            - name: Setup Premake5
              uses: abel0b/setup-premake@b80dc6f70e8ab159fb854bdadbeb1a53cfc28723
              with:
                version: 5.0.0-beta5
            - name: Add MSBuild to PATH
              uses: microsoft/setup-msbuild@v2
            - name: Compile ${{ matrix.configuration }}
              run: |
                premake5 vs2022
                vcpkg integrate install
                msbuild build/${{ env.name }}.sln /t:rebuild /p:Configuration=${{ matrix.configuration }}
            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with:
                name: ${{ env.name }}-${{ matrix.configuration }}
                if-no-files-found: error
                path: |
                  build/bin/**/*.asi
                  build/bin/**/*.dll
                  build/bin/**/*.exe
                  build/bin/**/*.pdb
